

3. Do think about your own interests very carefully and choose your topic within 3 weeks.

4. 【Please send answers to those questions to mqgao@kaikeba.com】
   Please answer some questions about our course. We do appreciate your help.
   4.1 What do you want to get in this course?
   4.2 What problems do you want to solve?
   4.3 What advantages do you have to accomplish your goal?
   4.4 What disadvantages you need to overcome to accomplish your goal?
   4.5 How will you plan to study in this course?
   

In [1]:
import cv2
import random
import numpy as np
from matplotlib import pyplot as plt

#### 1. Recode all examples

单通道灰度图

In [2]:
img_gray = cv2.imread('0.jpg', 0)
cv2.imshow("jrs",img_gray)

key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [3]:
# to show gray image to show image matrix
print(img_gray)

[[20 21 23 ... 21 21 21]
 [ 0  0  0 ...  2  2  2]
 [ 2  1  1 ...  2  2  2]
 ...
 [ 3 27 42 ... 86 78 70]
 [ 9 34 41 ... 88 81 74]
 [22 44 40 ... 89 83 76]]


In [4]:
# to show image data type
print(img_gray.dtype)

uint8


In [5]:
# to show gray image shape
print(img_gray.shape)  # h, w

(1103, 700)


三通道图

In [6]:
img = cv2.imread("0.jpg")
cv2.imshow("jrs",img)

key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [7]:
print(img)

[[[20 20 20]
  [21 21 21]
  [23 23 23]
  ...
  [21 21 21]
  [21 21 21]
  [21 21 21]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 2  2  2]
  [ 2  2  2]
  [ 2  2  2]]

 [[ 2  2  2]
  [ 1  1  1]
  [ 1  1  1]
  ...
  [ 2  2  2]
  [ 2  2  2]
  [ 2  2  2]]

 ...

 [[ 5  3  2]
  [29 27 26]
  [44 42 41]
  ...
  [72 92 80]
  [66 84 71]
  [58 76 63]]

 [[13  9  8]
  [38 34 33]
  [43 41 40]
  ...
  [74 94 82]
  [67 87 75]
  [60 80 68]]

 [[26 22 21]
  [48 44 43]
  [44 40 39]
  ...
  [75 94 85]
  [69 88 79]
  [62 81 72]]]


In [9]:
print(img.shape)

(1103, 700, 3)


图像裁剪

In [8]:
img_crop = img[0:100,0:200]
cv2.imshow("jrs_crop", img_crop)

key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

图像通道分离

In [12]:
B, G, R = cv2.split(img)

cv2.imshow("B",B)
cv2.imshow("G",G)
cv2.imshow("R",R)

key = cv2.waitKey()
if key==27:
    cv2.destroyAllWindows()

改变颜色

In [11]:
def random_light_color(img):
    # brightness
    B, G, R = cv2.split(img)

    for i in (B, G, R):
        rand = random.randint(-50, 50)
        if rand == 0:
            pass
        elif rand > 0:
            lim = 255 - rand
            i[i > lim] = 255
            i[i <= lim] = (rand + i[i <= lim]).astype(img.dtype)
        elif rand < 0:
            lim = 0 - rand
            i[i < lim] = 0
            i[i >= lim] = (rand + i[i >= lim]).astype(img.dtype)

    img_merge = cv2.merge((B, G, R))
    return img_merge

In [12]:
img_random_color = random_light_color(img)
cv2.imshow('img_random_color', img_random_color)

key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

伽马修正

#### 2. Please combine image crop, color shift, rotation and perspective transform together to complete a data augmentation script.

   Your code need to be completed in Python/C++ in .py or .cpp file with comments and readme file to indicate how to use.